#include "CodecState.hpp"
#include "CodecSets.hpp"
#include "subprocess.hpp"
#include "utils.hpp"

#include <string>
#include <format>
#include <vector>
#include <sstream>
#include <iomanip>
#include <filesystem>
#include <fstream>

static auto appdataPath = []() -> std::filesystem::path {
    wchar_t* appdata = nullptr;
    size_t len = 0;
    _wdupenv_s(&appdata, &len, L"APPDATA");
    if (appdata) {
        std::filesystem::path path(appdata);
        free(appdata);
        auto ret = path / "vfw-ffmpeg-bridge";

        std::error_code ec;
        std::filesystem::create_directories(ret, ec);
        if (ec) {
            MessageBoxW(nullptr, L"Failed to create settings directory.", L"VfW FFmpeg Bridge", MB_OK | MB_ICONERROR);
            return std::filesystem::path();
        }
        return ret;
    }
    return std::filesystem::path();
}();

std::wstring CodecState::GetQualityFlags() {
    const CodecSets::CodecInfo* info = CodecSets::GetCodecInfo(this->codec);
    if (!info || !info->formatQualityFlags) {
        return L"";
    }
    return info->formatQualityFlags(this->qualityMode, this->qualityValue1, this->qualityValue2);
}

std::wstring CodecState::GetAudioEncoderArgs() {
    if (this->audioCodec.empty()) {
        return L"";
    }

    std::wstring cmd = std::format(L"-c:a {} ", this->audioCodec);

    auto info = AudioSets::GetCodecInfo(this->audioCodec);
    if (info && info->formatQualityFlags) {
        cmd += info->formatQualityFlags(this->audioQualityMode, this->audioQualityValue);
    }

    return cmd;
}

std::wstring CodecState::GetFfmpegCommand() {
    std::wstring cmd = std::format(L"\"{}\" -y -f rawvideo -pix_fmt {} -s {}x{} -r {}/{} -i - ", 
                                  this->ffmpegPath, this->input_pix_fmt, this->width, this->height, this->fpsNum, this->fpsDen);

    if (!this->codec.empty()) {
        cmd += std::format(L"-c:v {} ", this->codec);
    }
    
    if (!this->preset.empty()) {
        cmd += std::format(L"-preset {} ", this->preset);
    }
    if (!this->tune.empty() && this->tune != L"(none)") {
        cmd += std::format(L"-tune {} ", this->tune);
    }

    cmd += this->GetQualityFlags() + L" ";

    if (!this->pix_fmt.empty()) {
        cmd += std::format(L"-pix_fmt {} ", this->pix_fmt);
    }
    if (this->shouldVFlip) {
        cmd += L"-vf \"vflip\" ";
    }
    cmd += L"-an ";
    if (!this->extra_args.empty()) {
        cmd += std::format(L"{} ", this->extra_args);
    }

    std::wstringstream pathEscaper;
    pathEscaper << std::quoted(this->path);
    cmd += pathEscaper.str();

    return cmd;
}

bool testCodec(std::wstring_view ffmpeg, std::wstring_view codec, int width, int height) {
    auto testCmd = std::format(L"\"{}\" -hide_banner -loglevel error -f lavfi -i nullsrc=s={}x{} -vframes 1 -c:v {} -f null -", ffmpeg, width, height, codec);
    return subprocess::Popen(testCmd).wait() == 0;
}

const wchar_t* determineBestCodec(std::wstring_view ffmpeg, int width, int height) {
    for (const auto& [name, info] : CodecSets::GetEncoders()) {
        if (testCodec(ffmpeg, name, width, height)) {
            return name.c_str();
        }
    }
    // libx264 takes everything, so getting to this code path implies
    // an error with the testing methodology
    return L"libx264";
}

QualityMode QualityUtils::GetDefaultQualityModeForCodec(std::wstring_view codec) {
    const CodecSets::CodecInfo* info = CodecSets::GetCodecInfo(codec);
    return info ? info->defaultQualityMode : QualityMode::None;
}

std::wstring GetAutoGeneratedName() {
    // e.g. 2026-07-05 17-23-54.mp4
    auto now = std::chrono::zoned_time{std::chrono::current_zone(), 
                                        std::chrono::system_clock::now()};
    auto local = std::chrono::floor<std::chrono::seconds>(now.get_local_time());
    return std::format(L"{:%Y-%m-%d %H-%M-%S}.mp4", local);
}

bool CodecState::SetRenderPath() {
    if (this->locationSelection == LocationSelection::Ask) {
        if (!this->path.empty()) {
            auto lastSlash = this->path.find_last_of(L"\\/");
            if (lastSlash != std::wstring::npos) {
                this->path = this->path.substr(0, lastSlash + 1);
            }
        }

        wchar_t fileBuffer[MAX_PATH] = {};
        if (!this->path.empty()) {
            wcsncpy_s(fileBuffer, (this->path + GetAutoGeneratedName()).c_str(), _TRUNCATE);
        } else {
            wcscpy_s(fileBuffer, GetAutoGeneratedName().c_str());
        }

        OPENFILENAMEW ofn = {};
        ofn.lStructSize = sizeof(ofn);
        ofn.hwndOwner = GetActiveWindow();
        ofn.lpstrFilter = L"MP4 Video (*.mp4)\0*.mp4\0MKV Video (*.mkv)\0*.mkv\0MOV Video (*.mov)\0*.mov\0All Files (*.*)\0*.*\0";
        ofn.lpstrFile = fileBuffer;
        ofn.nMaxFile = MAX_PATH;
        ofn.lpstrDefExt = L"mp4";
        ofn.Flags = OFN_OVERWRITEPROMPT | OFN_PATHMUSTEXIST | OFN_NOCHANGEDIR;

        if (GetSaveFileNameW(&ofn)) {
            this->path = fileBuffer;
            return true;
        } else {
            return false;
        }
    } else if (this->locationSelection == LocationSelection::NextToAvi) {
        auto path = TMAudio::GetAviFilePath();
        if(path.empty()) {
            return false;
        }

        this->path = path + L".mp4";
        return true;
    } else if (this->locationSelection == LocationSelection::Folder) {
        this->path = this->otherLocation + L"\\" + GetAutoGeneratedName();
        return true;
    }

    // invalid location selector value, should be unreachable code without corrupted settings file
    return false;
}

void CodecState::SetAutoDefaults() {
    if(!this->lastBestCodec.empty() && !this->lastBestCodec.starts_with(L"hevc") && testCodec(this->ffmpegPath, this->lastBestCodec, this->width ? this->width : 1920, this->height ? this->height : 1080)) {
        this->codec = this->lastBestCodec;
    } else {
        this->codec = determineBestCodec(this->ffmpegPath, this->width ? this->width : 1920, this->height ? this->height : 1080);
    }
    this->qualityMode = QualityUtils::GetDefaultQualityModeForCodec(this->codec);
    std::tie(this->qualityValue1, this->qualityValue2) = QualityUtils::GetDefaultQualityForMode(this->qualityMode);
    this->preset = L"";
    this->tune = L"";
    this->pix_fmt = L"yuv420p";
    this->extra_args = L"";
}

QualityDefaults QualityUtils::GetDefaultQualityForMode(QualityMode mode) {
    switch (mode) {
        case QualityMode::CBR:      return { 16000, 0 };
        case QualityMode::VBR:      return { 16000, 24000 };
        case QualityMode::CRF:      return { 21, 0 };
        case QualityMode::Lossless: return { 0, 0 };
        case QualityMode::CQP:      return { 24, 0 };
        case QualityMode::ABR:      return { 16000, 0 };
        case QualityMode::VBR_LAT:  return { 16000, 24000 };
        case QualityMode::QVBR:     return { 16000, 24000 };
        case QualityMode::HQVBR:    return { 16000, 24000 };
        case QualityMode::HQCBR:    return { 16000, 0 };
        case QualityMode::ICQ:      return { 24, 0 };
        default:                    return { 0, 0 };
    }
}

QualityMode QualityUtils::GetQualityModeFromString(const std::wstring& modeStr) {
    if (modeStr == L"CBR") return QualityMode::CBR;
    if (modeStr == L"VBR") return QualityMode::VBR;
    if (modeStr == L"CRF") return QualityMode::CRF;
    if (modeStr == L"Lossless") return QualityMode::Lossless;
    if (modeStr == L"CQP") return QualityMode::CQP;
    if (modeStr == L"ABR") return QualityMode::ABR;
    if (modeStr == L"VBR_LAT") return QualityMode::VBR_LAT;
    if (modeStr == L"QVBR") return QualityMode::QVBR;
    if (modeStr == L"HQVBR") return QualityMode::HQVBR;
    if (modeStr == L"HQCBR") return QualityMode::HQCBR;
    if (modeStr == L"ICQ") return QualityMode::ICQ;

    return QualityMode::None;
}

const wchar_t* QualityUtils::GetStringFromQualityMode(QualityMode mode) {
    switch (mode) {
        case QualityMode::CBR: return L"CBR";
        case QualityMode::VBR: return L"VBR";
        case QualityMode::CRF: return L"CRF";
        case QualityMode::Lossless: return L"Lossless";
        case QualityMode::CQP: return L"CQP";
        case QualityMode::ABR: return L"ABR";
        case QualityMode::VBR_LAT: return L"VBR_LAT";
        case QualityMode::QVBR: return L"QVBR";
        case QualityMode::HQVBR: return L"HQVBR";
        case QualityMode::HQCBR: return L"HQCBR";
        case QualityMode::ICQ: return L"ICQ";
        default: return L"";
    }
}

static constexpr const uint8_t SERIALIZER_VERSION = 1;

template<typename T>
void appendPrimitiveToBuffer(std::vector<uint8_t>& buffer, const T& data) {
    const uint8_t* byteData = reinterpret_cast<const uint8_t*>(&data);
    buffer.insert(buffer.end(), byteData, byteData + sizeof(T));
}

void appendWstringToBuffer(std::vector<uint8_t>& buffer, const std::wstring& str) {
    uint64_t len = str.size();
    appendPrimitiveToBuffer(buffer, len);
    buffer.insert(buffer.end(), reinterpret_cast<const uint8_t*>(str.data()), reinterpret_cast<const uint8_t*>(str.data()) + len * sizeof(wchar_t));
}

//for ICM_GETSTATE
std::vector<uint8_t> CodecState::Serialize() {
    std::vector<uint8_t> buffer;
    appendPrimitiveToBuffer(buffer, SERIALIZER_VERSION);

    appendWstringToBuffer(buffer, this->codec);
    appendWstringToBuffer(buffer, this->preset);
    appendWstringToBuffer(buffer, this->tune);
    appendWstringToBuffer(buffer, this->pix_fmt);
    appendWstringToBuffer(buffer, this->extra_args);
    appendWstringToBuffer(buffer, this->path);
    appendWstringToBuffer(buffer, this->otherLocation);
    appendWstringToBuffer(buffer, this->lastBestCodec);
    appendWstringToBuffer(buffer, this->audioCodec);
    appendWstringToBuffer(buffer, this->otherFfmpegPath);

    appendPrimitiveToBuffer(buffer, this->qualityMode);
    appendPrimitiveToBuffer(buffer, this->qualityValue1);
    appendPrimitiveToBuffer(buffer, this->qualityValue2);
    appendPrimitiveToBuffer(buffer, this->audioQualityMode);
    appendPrimitiveToBuffer(buffer, this->audioQualityValue);
    appendPrimitiveToBuffer(buffer, this->selectAuto);
    appendPrimitiveToBuffer(buffer, this->tmAudioHooks);
    appendPrimitiveToBuffer(buffer, this->locationSelection);
    appendPrimitiveToBuffer(buffer, this->ffmpegLocationMode);

    return buffer;
}

template <typename T>
T readPrimitiveFromBuffer(const std::vector<uint8_t>& buffer, size_t& offset) {
    if (offset + sizeof(T) > buffer.size()) {
        MessageBoxW(nullptr, L"An error has occured while reading your settings.\n(Attempted buffer overflow in readPrimitiveFromBuffer)", L"Error", MB_OK | MB_ICONERROR);
        return T{};
    }
    T data;
    std::memcpy(&data, buffer.data() + offset, sizeof(data));
    offset += sizeof(data);
    return data;
}

std::wstring readWstringFromBuffer(const std::vector<uint8_t>& buffer, size_t& offset) {
    uint64_t len = readPrimitiveFromBuffer<uint64_t>(buffer, offset);
    if (offset + len * sizeof(wchar_t) > buffer.size()) {
        MessageBoxW(nullptr, L"An error has occured while reading your settings.\n(Attempted buffer overflow in readWstringFromBuffer)", L"Error", MB_OK | MB_ICONERROR);
        return L"";
    }

    std::wstring str;
    str.assign(reinterpret_cast<const wchar_t*>(buffer.data() + offset), len);
    offset += len * sizeof(wchar_t);
    return str;
}

bool CodecState::Deserialize(const std::vector<uint8_t>& data) {
    size_t offset = 0;
    uint8_t version = readPrimitiveFromBuffer<uint8_t>(data, offset);
    if (version != SERIALIZER_VERSION) {
        MessageBoxW(nullptr, L"Saved VfW FFmpeg Bridge settings are incompatible with your current version, they will be reset.", L"Error", MB_OK | MB_ICONERROR);
        return false;
    }

    this->codec = std::move(readWstringFromBuffer(data, offset));
    this->preset = std::move(readWstringFromBuffer(data, offset));
    this->tune = std::move(readWstringFromBuffer(data, offset));
    this->pix_fmt = std::move(readWstringFromBuffer(data, offset));
    this->extra_args = std::move(readWstringFromBuffer(data, offset));
    this->path = std::move(readWstringFromBuffer(data, offset));
    this->otherLocation = std::move(readWstringFromBuffer(data, offset));
    this->lastBestCodec = std::move(readWstringFromBuffer(data, offset));
    this->audioCodec = std::move(readWstringFromBuffer(data, offset));
    this->otherFfmpegPath = std::move(readWstringFromBuffer(data, offset));

    this->qualityMode = readPrimitiveFromBuffer<QualityMode>(data, offset);
    this->qualityValue1 = readPrimitiveFromBuffer<int>(data, offset);
    this->qualityValue2 = readPrimitiveFromBuffer<int>(data, offset);
    this->audioQualityMode = readPrimitiveFromBuffer<AudioQualityMode>(data, offset);
    this->audioQualityValue = readPrimitiveFromBuffer<int>(data, offset);
    this->selectAuto = readPrimitiveFromBuffer<bool>(data, offset);
    this->tmAudioHooks = readPrimitiveFromBuffer<bool>(data, offset);
    this->locationSelection = readPrimitiveFromBuffer<LocationSelection>(data, offset);
    this->ffmpegLocationMode = readPrimitiveFromBuffer<FfmpegLocationMode>(data, offset);
    return true;
}

static std::filesystem::path settingsFile = appdataPath / "settings.bin";

void CodecState::Save() {
    auto blob = this->Serialize();
    std::ofstream ofs(settingsFile, std::ios::binary);
    if (!ofs) {
        MessageBoxW(nullptr, L"Failed to open settings file for writing.", L"VfW FFmpeg Bridge", MB_OK | MB_ICONERROR);
        return;
    }
    ofs.write(reinterpret_cast<const char*>(blob.data()), blob.size());
}

void CodecState::Load() {
    std::error_code ec;
    if (!std::filesystem::exists(settingsFile, ec) || ec) {
        return;
    }

    std::ifstream ifs(settingsFile, std::ios::binary);
    if (!ifs) {
        MessageBoxW(nullptr, L"Failed to open settings file for reading.", L"VfW FFmpeg Bridge", MB_OK | MB_ICONERROR);
        return;
    }

    std::vector<uint8_t> blob((std::istreambuf_iterator<char>(ifs)), std::istreambuf_iterator<char>());
    if (!this->Deserialize(blob)) {
        // error box already pops up in deserialize itself
        return;
    }
}

std::wstring getInstallDir() {
    WCHAR installDir[MAX_PATH];
    DWORD size = sizeof(installDir);

    LONG result = RegGetValueW(
        HKEY_LOCAL_MACHINE,
        L"Software\\vfw-ffmpeg-bridge",
        L"InstallDir",
        RRF_RT_REG_SZ,
        nullptr,
        installDir,
        &size
    );

    if (result != ERROR_SUCCESS) {
        return L"";
    }

    return std::wstring(installDir);
}

std::wstring getBundledFfmpegPath() {
    auto installDir = getInstallDir();
    if (installDir.empty()) {
        return L"";
    }
    return installDir + L"\\ffmpeg.exe";
}

std::pair<std::wstring, std::wstring> getWineFfmpegPaths() {
    auto installDir = getInstallDir();
    if (installDir.empty()) {
        return {L"", L""};
    }

    std::wstring dir = installDir + L"\\wine";
    return {dir + L"\\ffmpeg-x64.exe", dir + L"\\ffmpeg-x86.exe"};
}

bool testCommand(std::wstring_view command) {
    DWORD oldMode;
    SetThreadErrorMode(SEM_FAILCRITICALERRORS | SEM_NOOPENFILEERRORBOX, &oldMode);

    auto process = std::make_unique<subprocess::Popen>(std::wstring(command));
    auto ret = process->wait() == 0;

    SetThreadErrorMode(oldMode, nullptr);
    return ret;
}

std::wstring FfmpegLocationUtils::GetLinuxPath() {
    auto [wine64Path, wine32Path] = getWineFfmpegPaths();
    if (!wine64Path.empty() && testCommand(std::format(L"\"{}\" -version", wine64Path))) {
        return wine64Path;
    }
    if (!wine32Path.empty() && testCommand(std::format(L"\"{}\" -version", wine32Path))) {
        return wine32Path;
    }
    return L"";
}

bool FfmpegLocationUtils::IsLinuxAvailable() {
    return !GetLinuxPath().empty();
}

bool FfmpegLocationUtils::IsSystemAvailable() {
    return testCommand(L"ffmpeg -version");
}

std::wstring FfmpegLocationUtils::GetBundledPath() {
    auto adjacentPath = Bridge::GetAdjacentPath(Bridge::g_hInstance, L"ffmpeg.exe");
    if (!adjacentPath.empty() && std::filesystem::exists(adjacentPath)) {
        return adjacentPath;
    }

    auto bundledPath = getBundledFfmpegPath();
    if (!bundledPath.empty() && std::filesystem::exists(bundledPath)) {
        return bundledPath;
    }

    return L"";
}

bool FfmpegLocationUtils::IsBundledAvailable() {
    return !GetBundledPath().empty();
}

bool CodecState::FindBestFfmpeg() {
    for(auto& mode : {FfmpegLocationMode::Linux, FfmpegLocationMode::System, FfmpegLocationMode::Bundled}) {
        if(this->ApplyFfmpegLocation(mode)) {
            return true;
        }
    }

    return false;
}

bool CodecState::ApplyFfmpegLocation(FfmpegLocationMode mode) {
    switch (mode) {
        case FfmpegLocationMode::Linux: {
            auto path = FfmpegLocationUtils::GetLinuxPath();
            if (path.empty()) return false;
            this->ffmpegPath = path;
            this->ffmpegLocationMode = mode;
            return true;
        }
        case FfmpegLocationMode::System: {
            if (!FfmpegLocationUtils::IsSystemAvailable()) return false;
            this->ffmpegPath = L"ffmpeg";
            this->ffmpegLocationMode = mode;
            return true;
        }
        case FfmpegLocationMode::Bundled: {
            auto path = FfmpegLocationUtils::GetBundledPath();
            if (path.empty()) return false;
            this->ffmpegPath = path;
            this->ffmpegLocationMode = mode;
            return true;
        }
        case FfmpegLocationMode::Other: {
            if (this->otherFfmpegPath.empty() || !std::filesystem::exists(this->otherFfmpegPath)) return false;
            this->ffmpegPath = this->otherFfmpegPath;
            this->ffmpegLocationMode = mode;
            return true;
        }
    }
    return false;
}

void CodecState::ApplyFfmpeg() {
    if(this->ffmpegLocationMode == FfmpegLocationMode::Unknown) {
        FindBestFfmpeg();
    } else {
        ApplyFfmpegLocation(this->ffmpegLocationMode);
    }
}

void CodecState::Reset() {
    CodecState defaultState;
    *this = std::move(defaultState);
}