name: Build Binaries

on:
  workflow_dispatch:
  push:
    branches:
    - '**'

jobs:
  build-msvc:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: x86
          platform: Win32
        - name: x64
          platform: x64

    name: Build ${{ matrix.config.name }}
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v7
      with:
        submodules: recursive

    - name: Configure & Build
      run: |
        cmake -G "Visual Studio 17 2022" -B build -DCMAKE_BUILD_TYPE=Release -A ${{ matrix.config.platform }} -S .
        cmake --build build --config Release

    - name: Upload release build
      uses: actions/upload-artifact@v7
      with:
        name: vfw-ffmpeg-bridge_${{ matrix.config.name }}
        path: ./build/Release/

  build-installer:
    runs-on: windows-2022
    needs: build-msvc

    steps:
    - name: Checkout
      uses: actions/checkout@v7
      with:
        submodules: recursive

    - uses: actions/download-artifact@v4
      with:
        path: "${{ github.workspace }}/artifacts"

    - name: Prepare installer files
      run: |
        mkdir -p installer/files/x86
        mkdir -p installer/files/x64
        Copy-Item -Path "${{ github.workspace }}/artifacts/vfw-ffmpeg-bridge_x86/*.dll" -Destination installer/files/x86/
        Copy-Item -Path "${{ github.workspace }}/artifacts/vfw-ffmpeg-bridge_x64/*.dll" -Destination installer/files/x64/

    - name: Build installer
      run: |
        cd installer
        pip install requests
        python prepare-deps.py
        makensis installer.nsi

    - name: Upload installer
      uses: actions/upload-artifact@v7
      with:
        name: vfw-ffmpeg-bridge-installer
        path: installer/*.exe